export const ADMIN_JOBS_REQUEST = 'ADMIN_JOBS_REQUEST'
export const ADMIN_JOBS_SUCCESS = 'ADMIN_JOBS_SUCCESS'
export const ADMIN_JOBS_FAIL = 'ADMIN_JOBS_FAIL'

export const ALL_JOBS_REQUEST = 'ALL_JOBS_REQUEST'
export const ALL_JOBS_SUCCESS = 'ALL_JOBS_SUCCESS'
export const ALL_JOBS_FAIL = 'ALL_JOBS_FAIL'

export const JOB_DETAILS_REQUEST = 'JOB_DETAILS_REQUEST'
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS'
export const JOB_DETAILS_FAIL = 'JOB_DETAILS_FAIL'

export const DELETE_ALLJOB_REQUEST = 'DELETE_ALLJOB_REQUEST'
export const DELETE_ALLJOB_SUCCESS = 'DELETE_ALLJOB_SUCCESS'
export const DELETE_ALLJOB_RESET = 'DELETE_ALLJOB_RESET'
export const DELETE_ALLJOB_FAIL = 'DELETE_ALLJOB_FAIL'

export const SCRAPEDATA_REQUEST = 'SCRAPEDATA_REQUEST'
export const SCRAPEDATA_SUCCESS = 'SCRAPEDATA_SUCCESS'
export const SCRAPEDATA_RESET = 'SCRAPEDATA_RESET'
export const SCRAPEDATA_FAIL = 'SCRAPEDATA_FAIL'

export const DOWNLOAD_JOB_REQUEST = 'DOWNLOAD_JOB_REQUEST'
export const DOWNLOAD_JOB_SUCCESS = 'DOWNLOAD_JOB_SUCCESS'
export const DOWNLOAD_JOB_FAIL = 'DOWNLOAD_JOB_FAIL'
export const DOWNLOAD_JOB_RESET = 'DOWNLOAD_JOB_RESET'


export const DOWNLOAD_PROJECT_REQUEST = 'DOWNLOAD_PROJECT_REQUEST'
export const DOWNLOAD_PROJECT_SUCCESS = 'DOWNLOAD_PROJECT_SUCCESS'
export const DOWNLOAD_PROJECT_FAIL = 'DOWNLOAD_PROJECT_FAIL'
export const DOWNLOAD_PROJECT_RESET = 'DOWNLOAD_PROJECT_RESET'


export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'